// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AuthResponse auth response
//
// swagger:model AuthResponse
type AuthResponse struct {

	// access token
	AccessToken *TokenResponse `json:"access_token,omitempty"`

	// refresh token
	RefreshToken *TokenResponse `json:"refresh_token,omitempty"`

	// server time
	ServerTime int64 `json:"server_time,omitempty"`

	// user
	User *UserResponse `json:"user,omitempty"`
}

// Validate validates this auth response
func (m *AuthResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccessToken(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRefreshToken(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUser(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AuthResponse) validateAccessToken(formats strfmt.Registry) error {
	if swag.IsZero(m.AccessToken) { // not required
		return nil
	}

	if m.AccessToken != nil {
		if err := m.AccessToken.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("access_token")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("access_token")
			}
			return err
		}
	}

	return nil
}

func (m *AuthResponse) validateRefreshToken(formats strfmt.Registry) error {
	if swag.IsZero(m.RefreshToken) { // not required
		return nil
	}

	if m.RefreshToken != nil {
		if err := m.RefreshToken.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("refresh_token")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("refresh_token")
			}
			return err
		}
	}

	return nil
}

func (m *AuthResponse) validateUser(formats strfmt.Registry) error {
	if swag.IsZero(m.User) { // not required
		return nil
	}

	if m.User != nil {
		if err := m.User.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("user")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("user")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this auth response based on the context it is used
func (m *AuthResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAccessToken(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRefreshToken(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUser(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AuthResponse) contextValidateAccessToken(ctx context.Context, formats strfmt.Registry) error {

	if m.AccessToken != nil {

		if swag.IsZero(m.AccessToken) { // not required
			return nil
		}

		if err := m.AccessToken.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("access_token")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("access_token")
			}
			return err
		}
	}

	return nil
}

func (m *AuthResponse) contextValidateRefreshToken(ctx context.Context, formats strfmt.Registry) error {

	if m.RefreshToken != nil {

		if swag.IsZero(m.RefreshToken) { // not required
			return nil
		}

		if err := m.RefreshToken.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("refresh_token")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("refresh_token")
			}
			return err
		}
	}

	return nil
}

func (m *AuthResponse) contextValidateUser(ctx context.Context, formats strfmt.Registry) error {

	if m.User != nil {

		if swag.IsZero(m.User) { // not required
			return nil
		}

		if err := m.User.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("user")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("user")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AuthResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuthResponse) UnmarshalBinary(b []byte) error {
	var res AuthResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
