// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ChatMessageResponse chat message response
//
// swagger:model ChatMessageResponse
type ChatMessageResponse struct {

	// attachment mime type
	AttachmentMimeType string `json:"attachment_mime_type,omitempty"`

	// attachment type
	AttachmentType string `json:"attachment_type,omitempty"`

	// attachment url
	AttachmentURL string `json:"attachment_url,omitempty"`

	// content
	Content string `json:"content,omitempty"`

	// created at
	CreatedAt int64 `json:"created_at,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// sender id
	SenderID int64 `json:"sender_id,omitempty"`

	// sender name
	SenderName string `json:"sender_name,omitempty"`
}

// Validate validates this chat message response
func (m *ChatMessageResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this chat message response based on context it is used
func (m *ChatMessageResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ChatMessageResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChatMessageResponse) UnmarshalBinary(b []byte) error {
	var res ChatMessageResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
