// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ChatsResponse chats response
//
// swagger:model ChatsResponse
type ChatsResponse struct {

	// chats
	Chats []*ChatResponse `json:"chats"`
}

// Validate validates this chats response
func (m *ChatsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChats(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ChatsResponse) validateChats(formats strfmt.Registry) error {
	if swag.IsZero(m.Chats) { // not required
		return nil
	}

	for i := 0; i < len(m.Chats); i++ {
		if swag.IsZero(m.Chats[i]) { // not required
			continue
		}

		if m.Chats[i] != nil {
			if err := m.Chats[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("chats" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("chats" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this chats response based on the context it is used
func (m *ChatsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateChats(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ChatsResponse) contextValidateChats(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Chats); i++ {

		if m.Chats[i] != nil {

			if swag.IsZero(m.Chats[i]) { // not required
				return nil
			}

			if err := m.Chats[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("chats" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("chats" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ChatsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChatsResponse) UnmarshalBinary(b []byte) error {
	var res ChatsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
