// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ChatResponse chat response
//
// swagger:model ChatResponse
type ChatResponse struct {

	// doctor id
	DoctorID int64 `json:"doctor_id,omitempty"`

	// has unread
	HasUnread bool `json:"has_unread,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// last message
	LastMessage string `json:"last_message,omitempty"`

	// last message at
	LastMessageAt int64 `json:"last_message_at,omitempty"`

	// last message id
	LastMessageID int64 `json:"last_message_id,omitempty"`

	// last read message id
	LastReadMessageID int64 `json:"last_read_message_id,omitempty"`

	// other login
	OtherLogin string `json:"other_login,omitempty"`

	// other name
	OtherName string `json:"other_name,omitempty"`

	// other user id
	OtherUserID int64 `json:"other_user_id,omitempty"`

	// patient id
	PatientID int64 `json:"patient_id,omitempty"`

	// updated at
	UpdatedAt int64 `json:"updated_at,omitempty"`

	// unread count
	UnreadCount int64 `json:"unread_count,omitempty"`
}

// Validate validates this chat response
func (m *ChatResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this chat response based on context it is used
func (m *ChatResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ChatResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChatResponse) UnmarshalBinary(b []byte) error {
	var res ChatResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
