// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateChatRequest create chat request
//
// swagger:model CreateChatRequest
type CreateChatRequest struct {

	// doctor id
	// Required: true
	DoctorID *int64 `json:"doctor_id"`
}

// Validate validates this create chat request
func (m *CreateChatRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDoctorID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateChatRequest) validateDoctorID(formats strfmt.Registry) error {

	if err := validate.Required("doctor_id", "body", m.DoctorID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create chat request based on context it is used
func (m *CreateChatRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateChatRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateChatRequest) UnmarshalBinary(b []byte) error {
	var res CreateChatRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
