// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DoctorIDResponse doctor ID response
//
// swagger:model DoctorIDResponse
type DoctorIDResponse struct {

	// doctor id
	DoctorID int64 `json:"doctor_id,omitempty"`
}

// Validate validates this doctor ID response
func (m *DoctorIDResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this doctor ID response based on context it is used
func (m *DoctorIDResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DoctorIDResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DoctorIDResponse) UnmarshalBinary(b []byte) error {
	var res DoctorIDResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
