// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DoctorResponse doctor response
//
// swagger:model DoctorResponse
type DoctorResponse struct {

	// bio
	Bio string `json:"bio,omitempty"`

	// created at
	CreatedAt int64 `json:"created_at,omitempty"`

	// doctor code
	DoctorCode string `json:"doctor_code,omitempty"`

	// email
	Email string `json:"email,omitempty"`

	// first name
	FirstName string `json:"first_name,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// is verified
	IsVerified bool `json:"is_verified,omitempty"`

	// last name
	LastName string `json:"last_name,omitempty"`

	// license number
	LicenseNumber string `json:"license_number,omitempty"`

	// login
	Login string `json:"login,omitempty"`

	// middle name
	MiddleName string `json:"middle_name,omitempty"`

	// phone
	Phone string `json:"phone,omitempty"`

	// specialization
	Specialization string `json:"specialization,omitempty"`

	// updated at
	UpdatedAt int64 `json:"updated_at,omitempty"`
}

// Validate validates this doctor response
func (m *DoctorResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this doctor response based on context it is used
func (m *DoctorResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DoctorResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DoctorResponse) UnmarshalBinary(b []byte) error {
	var res DoctorResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
