// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DoctorCodeResponse doctor code response
//
// swagger:model DoctorCodeResponse
type DoctorCodeResponse struct {

	// doctor code
	// Example: DR-ABCD-1234
	DoctorCode string `json:"doctor_code,omitempty"`
}

// Validate validates this doctor code response
func (m *DoctorCodeResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this doctor code response based on context it is used
func (m *DoctorCodeResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DoctorCodeResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DoctorCodeResponse) UnmarshalBinary(b []byte) error {
	var res DoctorCodeResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

