// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DoctorCodeRequest doctor code request
//
// swagger:model DoctorCodeRequest
type DoctorCodeRequest struct {

	// doctor code
	// Example: DR-ABCD-1234
	// Required: true
	// Max Length: 128
	// Min Length: 3
	DoctorCode *string `json:"doctor_code"`
}

// Validate validates this doctor code request
func (m *DoctorCodeRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDoctorCode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DoctorCodeRequest) validateDoctorCode(formats strfmt.Registry) error {
	if err := validate.Required("doctor_code", "body", m.DoctorCode); err != nil {
		return err
	}

	if err := validate.MinLength("doctor_code", "body", *m.DoctorCode, 3); err != nil {
		return err
	}

	if err := validate.MaxLength("doctor_code", "body", *m.DoctorCode, 128); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this doctor code request based on context it is used
func (m *DoctorCodeRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DoctorCodeRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DoctorCodeRequest) UnmarshalBinary(b []byte) error {
	var res DoctorCodeRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

