// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// LoginRequest login request
//
// swagger:model LoginRequest
type LoginRequest struct {

	// access parameter
	// Example: ivanov@clinic.com
	// Required: true
	AccessParameter *string `json:"access_parameter"`

	// Human-readable device name for trusted-device enrollment
	DeviceName string `json:"device_name,omitempty"`

	// password
	// Example: SecurePass123!
	// Required: true
	Password *string `json:"password"`

	// Opaque trusted-device token returned by 2FA verification
	TrustedDeviceToken string `json:"trusted_device_token,omitempty"`
}

// Validate validates this login request
func (m *LoginRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccessParameter(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePassword(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *LoginRequest) validateAccessParameter(formats strfmt.Registry) error {

	if err := validate.Required("access_parameter", "body", m.AccessParameter); err != nil {
		return err
	}

	return nil
}

func (m *LoginRequest) validatePassword(formats strfmt.Registry) error {

	if err := validate.Required("password", "body", m.Password); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this login request based on context it is used
func (m *LoginRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *LoginRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LoginRequest) UnmarshalBinary(b []byte) error {
	var res LoginRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
