// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MarkChatReadRequest mark chat read request
//
// swagger:model MarkChatReadRequest
type MarkChatReadRequest struct {

	// last read message id
	LastReadMessageID *int64 `json:"last_read_message_id"`
}

// Validate validates this mark chat read request
func (m *MarkChatReadRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MarkChatReadRequest) validateLastReadMessageID(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this mark chat read request based on context it is used
func (m *MarkChatReadRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MarkChatReadRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MarkChatReadRequest) UnmarshalBinary(b []byte) error {
	var res MarkChatReadRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
