// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RecoveryCodesResponse recovery codes response
//
// swagger:model RecoveryCodesResponse
type RecoveryCodesResponse struct {

	// recovery codes
	RecoveryCodes []string `json:"recovery_codes"`
}

// Validate validates this recovery codes response
func (m *RecoveryCodesResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this recovery codes response based on context it is used
func (m *RecoveryCodesResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RecoveryCodesResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RecoveryCodesResponse) UnmarshalBinary(b []byte) error {
	var res RecoveryCodesResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
