// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// RegisterRequest register request
//
// swagger:model RegisterRequest
type RegisterRequest struct {

	// email
	// Example: ivanov@clinic.com
	// Required: true
	// Format: email
	Email *strfmt.Email `json:"email"`

	// first name
	// Example: Иван
	// Required: true
	FirstName *string `json:"first_name"`

	// last name
	// Example: Иванов
	// Required: true
	LastName *string `json:"last_name"`

	// login
	// Example: doctor.ivanov
	// Required: true
	// Max Length: 50
	// Min Length: 3
	Login *string `json:"login"`

	// middle name
	// Example: Иванович
	MiddleName string `json:"middle_name,omitempty"`

	// password
	// Example: SecurePass123!
	// Required: true
	// Max Length: 128
	// Min Length: 8
	Password *string `json:"password"`

	// phone
	// Example: +79991234567
	Phone string `json:"phone,omitempty"`

	// role
	// Example: doctor
	// Required: true
	// Enum: [admin doctor patient]
	Role *string `json:"role"`
}

// Validate validates this register request
func (m *RegisterRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFirstName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLastName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLogin(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePassword(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRole(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RegisterRequest) validateEmail(formats strfmt.Registry) error {

	if err := validate.Required("email", "body", m.Email); err != nil {
		return err
	}

	if err := validate.FormatOf("email", "body", "email", m.Email.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *RegisterRequest) validateFirstName(formats strfmt.Registry) error {

	if err := validate.Required("first_name", "body", m.FirstName); err != nil {
		return err
	}

	return nil
}

func (m *RegisterRequest) validateLastName(formats strfmt.Registry) error {

	if err := validate.Required("last_name", "body", m.LastName); err != nil {
		return err
	}

	return nil
}

func (m *RegisterRequest) validateLogin(formats strfmt.Registry) error {

	if err := validate.Required("login", "body", m.Login); err != nil {
		return err
	}

	if err := validate.MinLength("login", "body", *m.Login, 3); err != nil {
		return err
	}

	if err := validate.MaxLength("login", "body", *m.Login, 50); err != nil {
		return err
	}

	return nil
}

func (m *RegisterRequest) validatePassword(formats strfmt.Registry) error {

	if err := validate.Required("password", "body", m.Password); err != nil {
		return err
	}

	if err := validate.MinLength("password", "body", *m.Password, 8); err != nil {
		return err
	}

	if err := validate.MaxLength("password", "body", *m.Password, 128); err != nil {
		return err
	}

	return nil
}

var registerRequestTypeRolePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["admin","doctor","patient"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		registerRequestTypeRolePropEnum = append(registerRequestTypeRolePropEnum, v)
	}
}

const (

	// RegisterRequestRoleAdmin captures enum value "admin"
	RegisterRequestRoleAdmin string = "admin"

	// RegisterRequestRoleDoctor captures enum value "doctor"
	RegisterRequestRoleDoctor string = "doctor"

	// RegisterRequestRolePatient captures enum value "patient"
	RegisterRequestRolePatient string = "patient"
)

// prop value enum
func (m *RegisterRequest) validateRoleEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, registerRequestTypeRolePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *RegisterRequest) validateRole(formats strfmt.Registry) error {

	if err := validate.Required("role", "body", m.Role); err != nil {
		return err
	}

	// value enum
	if err := m.validateRoleEnum("role", "body", *m.Role); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this register request based on context it is used
func (m *RegisterRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RegisterRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RegisterRequest) UnmarshalBinary(b []byte) error {
	var res RegisterRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
