// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TwoFactorSetupResponse two factor setup response
//
// swagger:model TwoFactorSetupResponse
type TwoFactorSetupResponse struct {

	// otpauth url
	OtpauthURL string `json:"otpauth_url,omitempty"`

	// secret
	Secret string `json:"secret,omitempty"`
}

// Validate validates this two factor setup response
func (m *TwoFactorSetupResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this two factor setup response based on context it is used
func (m *TwoFactorSetupResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TwoFactorSetupResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TwoFactorSetupResponse) UnmarshalBinary(b []byte) error {
	var res TwoFactorSetupResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
