// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TwoFactorVerifyRequest two factor verify request
//
// swagger:model TwoFactorVerifyRequest
type TwoFactorVerifyRequest struct {

	// challenge id
	// Required: true
	// Format: uuid
	ChallengeID *strfmt.UUID `json:"challenge_id"`

	// code
	// Example: 123456
	Code string `json:"code,omitempty"`

	// device name
	DeviceName string `json:"device_name,omitempty"`

	// recovery code
	// Example: ABCDE-FGHIJ-KLMNO
	RecoveryCode string `json:"recovery_code,omitempty"`

	// trust device
	TrustDevice bool `json:"trust_device,omitempty"`
}

// Validate validates this two factor verify request
func (m *TwoFactorVerifyRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChallengeID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TwoFactorVerifyRequest) validateChallengeID(formats strfmt.Registry) error {

	if err := validate.Required("challenge_id", "body", m.ChallengeID); err != nil {
		return err
	}

	if err := validate.FormatOf("challenge_id", "body", "uuid", m.ChallengeID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this two factor verify request based on context it is used
func (m *TwoFactorVerifyRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TwoFactorVerifyRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TwoFactorVerifyRequest) UnmarshalBinary(b []byte) error {
	var res TwoFactorVerifyRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
