// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UserResponse user response
//
// swagger:model UserResponse
type UserResponse struct {

	// created at
	CreatedAt int64 `json:"created_at,omitempty"`

	// email
	// Example: ivanov@clinic.com
	Email string `json:"email,omitempty"`

	// first name
	FirstName string `json:"first_name,omitempty"`

	// id
	// Example: 1
	ID int64 `json:"id,omitempty"`

	// is verified
	// Example: false
	IsVerified bool `json:"is_verified,omitempty"`

	// last name
	LastName string `json:"last_name,omitempty"`

	// login
	// Example: doctor.ivanov
	Login string `json:"login,omitempty"`

	// middle name
	MiddleName string `json:"middle_name,omitempty"`

	// phone
	// Example: +79991234567
	Phone string `json:"phone,omitempty"`

	// role
	// Enum: [admin doctor patient]
	Role string `json:"role,omitempty"`

	// updated at
	UpdatedAt int64 `json:"updated_at,omitempty"`
}

// Validate validates this user response
func (m *UserResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRole(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var userResponseTypeRolePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["admin","doctor","patient"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		userResponseTypeRolePropEnum = append(userResponseTypeRolePropEnum, v)
	}
}

const (

	// UserResponseRoleAdmin captures enum value "admin"
	UserResponseRoleAdmin string = "admin"

	// UserResponseRoleDoctor captures enum value "doctor"
	UserResponseRoleDoctor string = "doctor"

	// UserResponseRolePatient captures enum value "patient"
	UserResponseRolePatient string = "patient"
)

// prop value enum
func (m *UserResponse) validateRoleEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, userResponseTypeRolePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *UserResponse) validateRole(formats strfmt.Registry) error {
	if swag.IsZero(m.Role) { // not required
		return nil
	}

	// value enum
	if err := m.validateRoleEnum("role", "body", m.Role); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this user response based on context it is used
func (m *UserResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserResponse) UnmarshalBinary(b []byte) error {
	var res UserResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
